language: php
php:
  - '7.4'
script:
  - mkdir -p build/logs/
  - php vendor/bin/phpunit --configuration test/phpunit.xml --coverage-clover ./build/logs/clover.xml
after_script:
  - php vendor/bin/php-coveralls -v
before_install:
  - composer require satooshi/php-coveralls
install:
  - composer install
